spring:
  config:
    import: classpath:config/.dev-config.yml

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        type: trace
        highlight_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /api/v1/
  error:
    include-message: always

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace